# Generated by Django 5.0.7 on 2024-07-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
    ]
